"""Typing surface for soma-provider."""
from collections.abc import Callable, Mapping
from typing import Any, Protocol, TypeVar, overload
from . import models as models
from ._componentize import ComponentizeFinding, ComponentizeReport, ComponentizeWheelEvidence, scan_componentize_compatibility

__version__: str
F = TypeVar("F", bound=Callable[..., Any])

class SomaProviderError(Exception): ...
class SchemaError(SomaProviderError): ...
class MetadataError(SomaProviderError): ...
class CapabilityUnavailableError(SomaProviderError): ...
class HttpResponse(dict[str, Any]): ...
class Request: ...
class Context:
    request: Request
    cancelled: bool
    async def http_json(self, method: str, url: str, *, headers: Mapping[str, str] | None = ..., body: Any = ...) -> Any: ...
    async def secret(self, name: str) -> str: ...
    async def state_get(self, key: str, default: Any = ...) -> Any: ...
    async def state_set(self, key: str, value: Any) -> None: ...
    async def info(self, message: str, **fields: Any) -> None: ...
    async def report_progress(self, current: int, *, total: int | None = ..., message: str | None = ...) -> None: ...
    async def check_cancelled(self) -> None: ...

@overload
def tool(function: F, /) -> F: ...
@overload
def tool(**metadata: Any) -> Callable[[F], F]: ...
def provider(**metadata: Any) -> dict[str, Any]: ...
def json_schema(annotation: Any) -> dict[str, Any]: ...
